### ISSUE TITLE
Supplement autoExec conguration in document description

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#225]
# Issue Template

## Description

In chain configuation chapter, the configuration description for autoExec is missing,
and the automatic execution chapter also needs supplementary content.

[Description of the issue]

**Expected behavior**: [What you expect to happen]
```
Contracts:
- SysConfig:
  - delayBlockNumber: 1
  - checkCallPermission: false
  - checkSendTxPermission: false
  - checkCreateContractPermission: false
  - checkQuota: false
  - checkFeeBackPlatform: false
  - chainOwner: '0x0000000000000000000000000000000000000000'
  - chainName: test-chain
  - chainId: 1
  - operator: test-operator
  - website: https://www.example.com
  - blockInterval: 3000
  - economicalModel: 0
  - name: Nervos AppChain Test Token
  - symbol: NATT
  - avatar: https://cdn.cryptape.com/icon_appchain.png
  - autoExec: false
- QuotaManager:
  - admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
```

**Actual behavior**: [What actually happens]
```
-Contracts:
 -SysConfig:
   delayBlockNumber: 1
   checkCallPermission: false
   checkSendTxPermission: false
   checkCreateContractPermission: false
   checkQuota: false
   checkFeeBackPlatform:false
   chainOwner: '0x0000000000000000000000000000000000000000'
   chainName: test-chain
   chainId: 1
   operator: test-operator
   website: https://www.example.com (https://www.example.com/)
   blockInterval: 3000
   economicalModel: 0
   name: Nervos AppChain Test Token
   symbol: NATT
   avatar: https://cdn.cryptape.com/icon_appchain.png
 -QuotaManager:
   admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
```

**Reproduce how often**: [What percentage of the time does it reproduce?]

## Versions

[The versions of the CITA, operating systems or VM software you use]

## Additional Information

[Any other information which would be helpful to reproduce the issue].
