### ISSUE TITLE
Yaml standard rules in create_init_data.py

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#609]
## Description

Yml usage in init_data does not follow [yml syntax](https://learn.getgrav.org/16/advanced/yaml).

[Description of the issue]

https://github.com/cryptape/cita/blob/develop/scripts/config_tool/create_init_data.py#L10-L51

```
Contracts:
- SysConfig:
  - delayBlockNumber: 1
  - checkCallPermission: false
  - checkSendTxPermission: false
  - checkCreateContractPermission: false
  - checkQuota: false
  - checkFeeBackPlatform: false
  - chainOwner: '0x0000000000000000000000000000000000000000'
  - chainName: test-chain
  - chainId: 1
  - operator: test-operator
  - website: https://www.example.com
  - blockInterval: 3000
  - economicalModel: 0
  - name: CITA Test Token
  - symbol: CTT
  - avatar: https://cdn.cryptape.com/icon_cita.png
  - autoExec: false
- QuotaManager:
  - admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
- NodeManager:
  - nodes:
    - '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
  - stakes:
    - 0
- ChainManager:
  - parentChainId: 0
  - parentChainAuthorities: []
- Authorization:
  - superAdmin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
- Group:
  - parent: '0x0000000000000000000000000000000000000000'
  - name: rootGroup
  - accounts:
    - '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
- Admin:
  - admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
- VersionManager:
  - version: 2
- PriceManager:
  - quotaPrice: 1000000
```

Standard Usage:

```
Contracts:
  SysConfig:
    delayBlockNumber: 1
    checkCallPermission: false
    checkSendTxPermission: false
    checkCreateContractPermission: false
    checkQuota: false
    checkFeeBackPlatform: false
    chainOwner: '0x0000000000000000000000000000000000000000'
    chainName: test-chain
    chainId: 1
    operator: test-operator
    website: https://www.example.com
    blockInterval: 3000
    economicalModel: 0
    name: CITA Test Token
    symbol: CTT
    avatar: https://cdn.cryptape.com/icon_cita.png
    autoExec: false
  QuotaManager:
    admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
  NodeManager:
    nodes:
      - '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
    stakes:
      - 0
  ChainManager:
    parentChainId: 0
    parentChainAuthorities: []
  Authorization:
    superAdmin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
  Group:
    parent: '0x0000000000000000000000000000000000000000'
    name: rootGroup
    accounts:
      - '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
  Admin:
    admin: '0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523'
  VersionManager:
    version: 2
  PriceManager:
    quotaPrice: 1000000

```
## Versions

[The versions of the CITA, operating systems or VM software you use]

## Additional Information

[Any other information which would be helpful to reproduce the issue].
