### ISSUE TITLE
fix skiped ci

### ISSUE THREAD

**Issue by ouwenkg** [cryptape/cita#656]
## fix skipped ci

[Description of the issue]

```
 "JSON-RPC Mock Test in Charge Mode":
    <<: *job-default
    steps:
      - restore_cache: *restore-source-codes-cache
      - restore_cache: *restore-release-cache
      - run: *after-restore-release-cache
      - run:
          name: JSON-RPC Mock Test in Quota Mode
          command: ./tests/integrate_test/cita_jsonrpc_schema_mock.sh quota
      - run:
          name: (Skip & TODO) JSON-RPC Mock Test in Charge Mode
          command: |
              echo "We should add it back later."
              # ./tests/integrate_test/cita_jsonrpc_schema_mock.sh charge
```

## Versions

v0.24
